apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-datavolume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
