apiVersion: v1

# This is a workaround for the broken  --from-file kubernetes abstraction
# which doesn't sanely handle .env files
# MYSQL_DATABASE and MYSQL_USER are both set to 'wordpress'

# INSTRUCTIONS:
# Generate a MYSQL_PASSWORD and MYSQL_ROOT_PASSWORD and then save this file before using it.
# e.g.
# echo && cat /dev/urandom | env LC_CTYPE=C tr -dc [:alnum:] | head -c 15 | base64 && echo


kind: Secret
metadata:
  name: db-secrets
  namespace: default

type: Opaque

data:
  MYSQL_DATABASE: d29yZHByZXNzCg==
  MYSQL_USER: d29yZHByZXNzCg==
  MYSQL_PASSWORD: SXhCMzRxRXF0dERubXpR
  MYSQL_ROOT_PASSWORD: TkdpSmk2QTQ2WUpUalR4
